### ISSUE TITLE
你好有个问题想请教一下！

### ISSUE THREAD

**Issue by xuziyue1998** [anrep/HousE#1]
请问：

为什么HousE一定要使用Householder Rotations呢？论文中似乎没有展示对比实验

理论证明2n次地套用Householder matrix等同于SO(k)也似乎不能表现该方案的必要性

为什么不简单地在k维空间来个k次的pRotatE呢，我想这大概也是SO(k)的

谢谢！

**Comment by rui9812** [comment]
Hi @xuziyue1998,

Thanks for your questions.

1. Why does HousE use Householder Rotation?
HousE uses Householder Rotation because it can naturally extend to arbitrary dimensional spaces for superior modeling capacity.

2. The necessity of using Householder rotations?
If this is what you want to ask, the Householder-based approach used in this paper is not the only way (there are others like Exponential Parametrization, etc.) to represent high-dimensional rotations, although it's the most elegant approach in my personal understanding.

3. In k-dimensional space, k times pRotatE?
pRotatE uses phase angles to represent rotations in a 2-D plane. I can't figure out how to use k two-dimensional rotations to represent arbitrary k-dimensional rotations, since the combination of two-dimensional rotations is still two-dimensional.

Thanks again for your attention.

Best Regards

**Comment by xuziyue1998** [comment]
作者 @rui9812，

你好，感谢回复！
HousE的效果确实非常好，这使我不得不多问些问题😀

对于1和2，我可以理解不使用指数参数化，也能理解多次的反射能表示旋转及其优雅性的原因。

不过论文公式(5)实际上还是相当于对一个K维向量左乘一个K维旋转矩阵是吧？那么不如直接用_k维静态欧拉角_来表达这种旋转？

正如我所描述的k次pRotatE，就是将实体集合建模为R^{ |E| x D x K }，其中|E|表示实体数量，D是emb维度，K是论文中描述的row vector的大小。 先在K维中点对点地计算角度差——sin(h + r - t)，再使用某种范数计算出K维总体的角度差。

我想问这是不是也算是SO(K)的？如果这也是属于SO(K)的话，应该是比Householder Rotation简单一些的吧😀

虽然这样就不能伸缩了，不能拓展成Householder投影了。

期待你的指教！
祝好！

**Comment by rui9812** [comment]
Hi @xuziyue1998,

1. 论文公式(5)实际上还是相当于对一个K维向量左乘一个K维旋转矩阵是吧？
Yes, your understanding is correct.

2. k维静态欧拉角? 这是不是也算是SO(K)的？
In my opinion, the answer is **No**. Your idea is to use K phase angles to represent arbitrary K-dimensional rotations. Unfortunately, for K-dimensional rotations, there are K(K−1)/2 degrees of freedom, which means we need K(K-1)/2 independent parameters to model K-dimensional rotations. For example, rotations in 4-dimensional space have 6 degrees of freedom, we need 6 independent parameters (rather than 4 phase angles) to represent such rotations. Moreover, using Euler angles to represent rotations has the problem of Gimbal Lock.

Thanks for your questions and attention.

Best Regards

**Comment by xuziyue1998** [comment]
谢谢，感谢指点

确实是自由度不够了

不过万向锁对于静态欧拉角应该是不存在的

再次感谢
